export const USER_AUTHENTICATED = 'USER_AUTHENTICATED';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_AUTHENTICATION_REQUEST = 'USER_AUTHENTICATION_REQUEST';
export const USER_SIGNUP_REQUEST = 'USER_SIGNUP_REQUEST';
export const USER_AUTHENTICATION_ERR = 'USER_AUTHENTICATION_ERR';
export const REGISTER_NEW_SAGAS = 'REGISTER_NEW_SAGAS';
